name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
template: |
  ## What’s Changed

  $CHANGES

categories:
  - title: "🚀 Features"
    labels:
      - 'feature'
      - 'enhancement'
  - title: "🐛 Bug Fixes"
    labels:
      - 'fix'
      - 'bug'
  - title: "💚 Maintenance"
    labels:
      - 'chore'
      - 'documentation'
  - title: "🧱 Dependencies"
    labels:
      - 'dependencies'
      - 'type: dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'chore'
      - 'documentation'
      - 'dependencies'
  default: patch
exclude-labels:
  - 'skip-changelog'
