name: CI
on:
  pull_request:
jobs:
  ci-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci: [ "ci11", "ci17", "ci21" ]
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 100
          fetch-tags: true
      - name: Install nix
        uses: cachix/install-nix-action@v27
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: sbt ${{ matrix.ci }} (${{ github.ref }})
        run: nix develop .#${{ matrix.ci }} --command sbt ci
  ci:
    runs-on: ubuntu-latest
    needs: [ci-matrix]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"
